### ISSUE TITLE
`Iri<String>` is a waste of space

### ISSUE THREAD

**Issue by pchampin** [oxigraph/rio#10]
I notice that the "default" type parameter for `Iri<T>` (i.e. the one used in many places in the crate) is `String`.

I would suggest switching to `Box<str>`, which consumes 33% less memory (16 bytes instead of 24 bytes). The only benefit of `String` over `Box<str>` is mutability, which is not needed here (Iri are conceptually immutable, right?).

If you agree about that, I can propose a pull request.

**Comment by Tpt** [comment]
Indeed, it could save some space even if it's quite artificial imho to just compute the size of the stack data and not also the size of the pointed data for uniquely owned values.

It seems that most of people who write rust code are using `String` everywhere so keeping it into the public API is probably a good idea to keep it nice.

Feel free to do a PR for the internal values but it seems to me (I have not done any bench trying this change) that there would be a lot of optimization spots with better return on investment.

For example, we do two validation phases for IRIs when parsing NTriples (one matching the NTriples syntax, the other one the IRI syntax). The decoding of not ascii characters with `read_utf8_char` seems quite slow and the line by line buffering in `LookAheadLineBasedByteReader` is probably not the most efficient approach.

**Comment by pchampin** [comment]
> it's quite artificial imho to just compute the size of the stack data and not also the size of the pointed data for uniquely owned values

You are right, I got carried away when writing "33% less memory" ;-)
Still, all the IRIs stored in a graph add up, and I think this could still make a difference.
Although I also agree that

> there would be a lot of optimization spots with better return on investment.

**Comment by Tpt** [comment]
> Still, all the IRIs stored in a graph add up, and I think this could still make a difference.

With the current implementation for Turtle `Iri<String>` is only allocated for each prefix so it should not be much. For NTriples, there is no `Iri<String>` used. For RDF/XML there is a number of `Iri<String>` allocated linear according to the maximum amount of XML tag nesting and the number of prefixes. So, it might save a few kb but not much more.

**Comment by pchampin** [comment]
I realize that this has been lingering, while I have been convinced that this is not really an issue.
