### ISSUE TITLE
Add Turtle* support

### ISSUE THREAD

**Issue by Tpt** [oxigraph/rio#29]
It would be nice to add support of [Turtle*](https://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/) (any Maybe NTriples*, NQuads* and TriG*) to Rio.

This could be done by adding a disabled by default "star" feature that would add `Triple` to the term enumeration and renaming the `NamedAndBlankNode` enumeration to something like `Node` with also a `Triple` variant.

**Comment by pchampin** [comment]
This is solved by release 0.6.0; isn'it?

**Comment by Tpt** [comment]
Yes :-)
