### ISSUE TITLE
Assistance with MRE

### ISSUE THREAD

**Issue by mattcollier** [oxigraph/rio#32]
Hello, thank you all very much for putting this together.  As a newcomer to Rust and this module, I'm trying to sort out this pattern.  I can' seem to sort out the proper incantation for lifetimes etc to make this work.  I've spent quite a while doing research and trying lifetimes in various combinations.  Can this be made to work?  Or maybe I'm just doing it wrong entirely?

I don't know what if anything in this construction has the same lifetime (or can be made to have the same lifetime) as `some_vec`.

Thanks!

```rust
use rio_turtle::{NQuadsParser, TurtleError};
use rio_api::parser::QuadsParser;
use rio_api::model::{NamedOrBlankNode};

fn main() {
    let file = b"<http://example.com/foo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> <http://example.com/> .
    <http://example.com/foo> <http://schema.org/name> \"Foo\" <http://example.com/> .
    <http://example.com/bar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
    <http://example.com/bar> <http://schema.org/name> \"Bar\" .";

    let count = do_work(file);
    println!("count {}", count);
}

#[allow(unused_must_use)]
fn do_work(file: &[u8]) -> i32 {
    let mut count = 0;
    let mut some_vec: Vec<&str> = Vec::new();
    NQuadsParser::new(file.as_ref()).parse_all(&mut |t| {
        let id = match t.subject {
            NamedOrBlankNode::NamedNode(node) => node.iri,
            NamedOrBlankNode::BlankNode(node) => node.id,
          };
        some_vec.push(id);
        count += 1;
        Ok(()) as Result<(), TurtleError>
    });
    count
}
```

The compiler error: 
```
~/dev/basic-rio$ cargo build
   Compiling basic-rio v0.1.0 (/home/matt/dev/basic-rio)
error[E0521]: borrowed data escapes outside of closure
  --> src/main.rs:24:9
   |
18 |     let mut some_vec: Vec<&str> = Vec::new();
   |         ------------ `some_vec` declared here, outside of the closure body
19 |     NQuadsParser::new(file.as_ref()).parse_all(&mut |t| {
   |                                                      - `t` is a reference that is only valid in the closure body
...
24 |         some_vec.push(id);
   |         ^^^^^^^^^^^^^^^^^ `t` escapes the closure body here

error: aborting due to previous error

error: could not compile `basic-rio`

To learn more, run the command again with --verbose.

```

**Comment by Tpt** [comment]
Hi! The parsers returns `&str` that points to internal buffers. These buffers lifetime is limited to the `parse_all` closure. Your code attempt to make these `&str` references "escape" the closure by appending them inside of the `some_vec` array.

To solve this problem you could make the `some_vec` contain `String` buffers and not `&str` references:

```rust
use rio_turtle::{NQuadsParser, TurtleError};
use rio_api::parser::QuadsParser;
use rio_api::model::{NamedOrBlankNode};

fn main() {
    let file = b"<http://example.com/foo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> <http://example.com/> .
    <http://example.com/foo> <http://schema.org/name> \"Foo\" <http://example.com/> .
    <http://example.com/bar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
    <http://example.com/bar> <http://schema.org/name> \"Bar\" .";

    let count = do_work(file);
    println!("count {}", count);
}

#[allow(unused_must_use)]
fn do_work(file: &[u8]) -> i32 {
    let mut count = 0;
    let mut some_vec: Vec<String> = Vec::new();
    NQuadsParser::new(file.as_ref()).parse_all(&mut |t| {
        let id = match t.subject {
            NamedOrBlankNode::NamedNode(node) => node.iri,
            NamedOrBlankNode::BlankNode(node) => node.id,
          };
        some_vec.push(id.to_owned());
        count += 1;
        Ok(()) as Result<(), TurtleError>
    });
    count
}
```

**Comment by mattcollier** [comment]
@Tpt Thank you for your help.  I believe `to_owned` is effectively a clone, is that correct?  I failed to mention in my OP that I am specifically trying to avoid a copy (that's already happening in an existing implementation).  :)   Rio has done a great job of parsing the data quickly, I'm hoping *not* to slow things down by adding an additional copy operation.

**Comment by Tpt** [comment]
>  believe to_owned is effectively a clone, is that correct? 

Yes, exactly.

> I'm hoping not to slow things down by adding an additional copy operation.

Rio is not very well optimized yet and does quite a lot of copies. So I believe it won't slow down the code much. I would be more afraid of the allocation required by `to_owned` but avoiding it seems complicated to me.

**Comment by mattcollier** [comment]
I think this is just a restatement of the same issue.  Are there primitives in place that would allow for and API like this?

```
let quads: Vec<rio_api::model::Quad> = some_rio_quad_parser_api(file); 
```

**Comment by mattcollier** [comment]
In studying the rio implementation I think I just connected some dots.  :)  So, one of the things that makes rio fast is that it's reusing the SAME pre-allocated memory as a read buffer. 
- Forms a Quad from the buffer
- Send the Quad into the closure
- Do something with the Quad in the closure
- After closure, the SAME memory/buffer is used for the next Quad
- Repeat

Therefore, there is no memory address that contains the values from the Quad in the closure as that memory is now being used for the next read cycle.

Do I have the right mental model for this now?

**Comment by mattcollier** [comment]
And if that is the case.  I wonder if an API like this might provide some use:
```
let buffer = SomeBufferContainingN-Quads; // (empty or populated?)
// this might also work with existing API if lifetimes can be sorted
let quads: Vec<rio_api::model::Quad> = some_rio_quad_parser_api(file); 
// the idea now is that `buffer` still has a representation of the memory for all the quads.
```

**Comment by Tpt** [comment]
> So, one of the things that makes rio fast is that it's reusing the SAME pre-allocated memory as a read buffer.
> Do I have the right mental model for this now?

Yes, exactly. Sorry for not stressing it earlier. I believe it is also the design of [Serd](https://github.com/drobilla/serd/) that is significantly faster than Rio.

```
let buffer = SomeBufferContainingN-Quads; // (empty or populated?)
// this might also work with existing API if lifetimes can be sorted
let quads: Vec<rio_api::model::Quad> = some_rio_quad_parser_api(file); 
// the idea now is that `buffer` still has a representation of the memory for all the quads.
```
Sadly, I am afraid it would be hard to make it work because N-Quads allows to escape characters. So, the term values are not always exactly contained in the input buffer.

Something that might be interesting is to benchmark your code with and without `some_vec` filling to get an idea of how much time is actually spent building `some_vec`.

Anyway, if you find an efficient way to make RIo return "owned" data it would be much appreciated.

**Comment by mattcollier** [comment]
@Tpt Happy New Year and thank you very much for your time in helping me understand the design.  Closing.

**Comment by Tpt** [comment]
@mattcollier Thank you! Happy new year to you too!
