### ISSUE TITLE
Wrong namespace splitting in XML formatter

### ISSUE THREAD

**Issue by pchampin** [oxigraph/rio#37]
Given the following triple:
```
<http://example.org/s> <http://example.org/properties:p> "o".
```
the XML formatter produces (indentation added for readability):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="http://example.org/s">
        <properties:p xmlns="http://example.org/" rdf:datatype="http://www.w3.org/2001/XMLSchema#string">o</properties:p>
  </rdf:Description>
</rdf:RDF>
```
which is invalid because of `property:p` (no namespace `property` is defined).

Note that Wikidata has IRIs with this structure.

When looking for a split point between namespace and prefix, the formatter should also split on `:`.

**Comment by Tpt** [comment]
Thank you for finding this problem! It should be fixed now in the `master` branch
