### ISSUE TITLE
parser mixes its own blank node labels with those from the graph

### ISSUE THREAD

**Issue by pchampin** [oxigraph/rio#46]
Consider the following Turtle snippet:
```
:alice :likes [ :name "bob" ].
_:riog00000001 <tag:name> "charlie".    
```
It is parsed as
```
:alice :likes [ :name "bob", "charlie" ].
```
which is a mistake.

A simple workaround would be to detect and alter any bnode label in the source that matches `riog[0-9]{8}`

**Comment by Tpt** [comment]
The fix is now released in v0.6.1
